<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>DriveSync.WPF</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.1" />
		<PackageReference Include="Serilog" Version="3.1.1" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="TaskScheduler" Version="2.11.0" />
	</ItemGroup>

	<ItemGroup>
		<Page Update="Styles\Colors.xaml">
			<SubType>Designer</SubType>
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Styles\Typography.xaml">
			<SubType>Designer</SubType>
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Themes\DarkTheme.xaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Page>
		<Page Update="Themes\LightTheme.xaml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Page>
	</ItemGroup>

</Project>